/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as MyIndexRouteImport } from './routes/my/index'
import { Route as InterestIndexRouteImport } from './routes/interest/index'
import { Route as DiscoveryIndexRouteImport } from './routes/discovery/index'
import { Route as TestCreateRouteImport } from './routes/test/create'
import { Route as DiscoveryTestIdRouteImport } from './routes/discovery/$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/my/',
  path: '/my/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestIndexRoute = InterestIndexRouteImport.update({
  id: '/interest/',
  path: '/interest/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryIndexRoute = DiscoveryIndexRouteImport.update({
  id: '/discovery/',
  path: '/discovery/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCreateRoute = TestCreateRouteImport.update({
  id: '/test/create',
  path: '/test/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryTestIdRoute = DiscoveryTestIdRouteImport.update({
  id: '/discovery/$testId',
  path: '/discovery/$testId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discovery/$testId': typeof DiscoveryTestIdRoute
  '/test/create': typeof TestCreateRoute
  '/discovery/': typeof DiscoveryIndexRoute
  '/interest/': typeof InterestIndexRoute
  '/my/': typeof MyIndexRoute
  '/test/': typeof TestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discovery/$testId': typeof DiscoveryTestIdRoute
  '/test/create': typeof TestCreateRoute
  '/discovery': typeof DiscoveryIndexRoute
  '/interest': typeof InterestIndexRoute
  '/my': typeof MyIndexRoute
  '/test': typeof TestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discovery/$testId': typeof DiscoveryTestIdRoute
  '/test/create': typeof TestCreateRoute
  '/discovery/': typeof DiscoveryIndexRoute
  '/interest/': typeof InterestIndexRoute
  '/my/': typeof MyIndexRoute
  '/test/': typeof TestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discovery/$testId'
    | '/test/create'
    | '/discovery/'
    | '/interest/'
    | '/my/'
    | '/test/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discovery/$testId'
    | '/test/create'
    | '/discovery'
    | '/interest'
    | '/my'
    | '/test'
  id:
    | '__root__'
    | '/'
    | '/discovery/$testId'
    | '/test/create'
    | '/discovery/'
    | '/interest/'
    | '/my/'
    | '/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoveryTestIdRoute: typeof DiscoveryTestIdRoute
  TestCreateRoute: typeof TestCreateRoute
  DiscoveryIndexRoute: typeof DiscoveryIndexRoute
  InterestIndexRoute: typeof InterestIndexRoute
  MyIndexRoute: typeof MyIndexRoute
  TestIndexRoute: typeof TestIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/': {
      id: '/my/'
      path: '/my'
      fullPath: '/my/'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interest/': {
      id: '/interest/'
      path: '/interest'
      fullPath: '/interest/'
      preLoaderRoute: typeof InterestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/': {
      id: '/discovery/'
      path: '/discovery'
      fullPath: '/discovery/'
      preLoaderRoute: typeof DiscoveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/create': {
      id: '/test/create'
      path: '/test/create'
      fullPath: '/test/create'
      preLoaderRoute: typeof TestCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery/$testId': {
      id: '/discovery/$testId'
      path: '/discovery/$testId'
      fullPath: '/discovery/$testId'
      preLoaderRoute: typeof DiscoveryTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoveryTestIdRoute: DiscoveryTestIdRoute,
  TestCreateRoute: TestCreateRoute,
  DiscoveryIndexRoute: DiscoveryIndexRoute,
  InterestIndexRoute: InterestIndexRoute,
  MyIndexRoute: MyIndexRoute,
  TestIndexRoute: TestIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
