/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestCreateRouteImport } from './routes/test-create'
import { Route as IndexRouteImport } from './routes/index'

const TestCreateRoute = TestCreateRouteImport.update({
  id: '/test-create',
  path: '/test-create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-create': typeof TestCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-create': typeof TestCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test-create': typeof TestCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test-create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-create'
  id: '__root__' | '/' | '/test-create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestCreateRoute: typeof TestCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-create': {
      id: '/test-create'
      path: '/test-create'
      fullPath: '/test-create'
      preLoaderRoute: typeof TestCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestCreateRoute: TestCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
